// src/components/modal/index.tsx
'use client';

import { useModalStore } from '@/src/stores/modal.store';
import { useNavigationStore } from '@/src/stores/navigation.store';
import { useEffect, useState } from 'react';

interface ModalComponentProps {
  componentFocused: boolean;
}

export default function ModalComponent(props: ModalComponentProps) {
  const [activeButtonIndex, setActiveButtonIndex] = useState(0);
  const { pressLeftEvent, pressRightEvent, pressEnterEvent, pressBackEvent } =
    useNavigationStore();
  const { closeModal } = useModalStore();

  useEffect(() => {
    const navigateLeft = () => {
      if (activeButtonIndex > 0 && props.componentFocused) {
        setActiveButtonIndex(activeButtonIndex - 1);
      }
    };
    pressLeftEvent && navigateLeft();
  }, [pressLeftEvent]);

  useEffect(() => {
    const navigateRight = () => {
      if (activeButtonIndex < 1 && props.componentFocused) {
        setActiveButtonIndex(activeButtonIndex + 1);
      }
    };
    pressRightEvent && navigateRight();
  }, [pressRightEvent]);

  useEffect(() => {
    const enterPress = () => {
      if (activeButtonIndex === 0 && props.componentFocused) {
        window.close();
      } else if (activeButtonIndex === 1 && props.componentFocused) {
        closeModal();
      }
    };
    pressEnterEvent && enterPress();
  }, [pressEnterEvent]);

  return (
    <div className="fixed top-0 left-0 right-0 bottom-0 flex justify-center items-center backdrop-blur-md">
      <div className="bg-white p-14 text-black rounded-lg text-2xl">
        <h2 className="text-4xl mb-4">Exit</h2>
        <p className="mb-10">Are you sure you want to close the app?</p>
        <div className="flex justify-between">
          <button
            className={
              `appearance-none rounded-lg p-4 min-w-40 ` +
              (activeButtonIndex === 0
                ? 'text-white bg-neutral-950'
                : 'bg-neutral-200')
            }
          >
            Yes
          </button>
          <button
            className={
              `appearance-none rounded-lg p-4 min-w-40 ` +
              (activeButtonIndex === 1
                ? 'text-white bg-neutral-950'
                : 'bg-neutral-200')
            }
          >
            No
          </button>
        </div>
      </div>
    </div>
  );
}

// src/app/components/modal/modal.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { NavigationService } from '../../services/navigation.service';
import { ModalService } from '../../services/modal.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './modal.component.html',
  styleUrl: './modal.component.scss',
})
export class ModalComponent implements OnInit {
  @Input() componentFocused: boolean = false;
  activeButtonIndex: number = 0;
  leftPressSubscription: Subscription | null = null;
  rightPressSubscription: Subscription | null = null;
  enterPressSubscription: Subscription | null = null;
  backPressSubscription: Subscription | null = null;

  constructor(
    private modalService: ModalService,
    private navigationService: NavigationService,
  ) {}

  ngOnInit() {
    this.leftPressSubscription =
      this.navigationService.leftNavigation.subscribe(() =>
        this.navigateLeft(),
      );
    this.rightPressSubscription =
      this.navigationService.rightNavigation.subscribe(() =>
        this.navigateRight(),
      );
    this.enterPressSubscription =
      this.navigationService.enterNavigation.subscribe(() => this.enterPress());
    this.backPressSubscription =
      this.navigationService.backNavigation.subscribe(() => this.backPress());
  }

  private navigateLeft() {
    if (this.activeButtonIndex > 0 && this.componentFocused) {
      this.activeButtonIndex--;
    }
  }

  private navigateRight() {
    if (this.activeButtonIndex < 1 && this.componentFocused) {
      this.activeButtonIndex++;
    }
  }

  private enterPress() {
    if (this.activeButtonIndex === 0 && this.componentFocused) {
      window.close();
    } else if (this.activeButtonIndex === 1 && this.componentFocused) {
      this.modalService.closeModal();
    }
  }

  private backPress() {
    if (this.componentFocused) {
      this.modalService.closeModal();
    }
  }

  ngOnDestroy() {
    this.leftPressSubscription?.unsubscribe();
    this.rightPressSubscription?.unsubscribe();
    this.enterPressSubscription?.unsubscribe();
    this.backPressSubscription?.unsubscribe();
  }
}

<div class="fixed top-0 left-0 right-0 bottom-0 flex justify-center items-center backdrop-blur-md">
    <div class="bg-white p-14 text-black rounded-lg text-2xl">
        <h2 class="text-4xl mb-4">Exit</h2>
        <p class="mb-10">Are you sure you want to close the app?</p>
        <div class="flex justify-between">
            <button class="appearance-none rounded-lg p-4 min-w-40"
                [ngClass]="activeButtonIndex === 0 ? 'text-white bg-neutral-950' : 'bg-neutral-200'">Yes</button>
            <button class="appearance-none rounded-lg p-4 min-w-40"
                [ngClass]="activeButtonIndex === 1 ? 'text-white bg-neutral-950' : 'bg-neutral-200'">No</button>
        </div>
    </div>
</div>
